"""Add photo_filename column to Recipe

Revision ID: 49bf5bcfc586
Revises: clear_tables
Create Date: 2023-11-23 16:07:46.734751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bf5bcfc586'
down_revision = 'clear_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('photo_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'photo_filename')
    # ### end Alembic commands ###
