"""added is_saved flag to recipes

Revision ID: f92e14e04f12
Revises: d8ca95ffd9af
Create Date: 2023-12-12 15:35:05.337545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92e14e04f12'
down_revision = 'd8ca95ffd9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_saved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('is_saved')

    # ### end Alembic commands ###
